sites:
  project_name: # First parameter for the command
    dev: # Second parameter
      ssh_config: "" # SSH alias or connection string.
      compose_file: "" # Absolute path for docker-compose file.
      service_group: "" # Docker environment name.
      app_name: "" # Main application name. Only used when running force restart for service.
    stage: # Second parameter
      ssh_config: "" # SSH alias or connection string.
      compose_file: "" # Docker-compose file name.
      service_group: "" # Docker environment name.
      app_name: "" # Main application name. Only used when running force restart for service.
  project_name_2:
    stage:
      ssh_config: "" # SSH alias or connection string.
      compose_file: "" # Docker-compose file name.
      service_group: "" # Docker environment name.
      app_name: "" # Main application name. Only used when running force restart for service.
