sites:
  project_name: # First parameter for the command
    dev: # Second parameter
      ssh_config: "" # SSH alias or connection string.
      compose_file: "" # Absolute path for docker-compose file.
      docker_env: "" # Docker environment name.
    stage: # Second parameter
      ssh_config: "" # SSH alias or connection string.
      compose_file: "" # Docker-compose file name.
      docker_env: "" # Docker environment name.
  project_name_2:
    stage:
      ssh_config: ""
      compose_file: ""
      docker_env: ""
